# -*- coding: utf-8 -*-
"""
/***************************************************************************
 TestUI
                                 A QGIS plugin
 Testing an interface integration
 Generated by Plugin Builder: http://g-sherman.github.io/Qgis-Plugin-Builder/
                             -------------------
        begin                : 2024-04-01
        copyright            : (C) 2024 by Eli Simonson
        email                : esimonson@clarku.edu
        git sha              : $Format:%H$
 ***************************************************************************/

/***************************************************************************
 *                                                                         *
 *   This program is free software; you can redistribute it and/or modify  *
 *   it under the terms of the GNU General Public License as published by  *
 *   the Free Software Foundation; either version 2 of the License, or     *
 *   (at your option) any later version.                                   *
 *                                                                         *
 ***************************************************************************/
 This script initializes the plugin, making it known to QGIS.
"""


# noinspection PyPep8Naming
def classFactory(iface):  # pylint: disable=invalid-name
    """Load TestUI class from file TestUI.

    :param iface: A QGIS interface instance.
    :type iface: QgsInterface
    """
    #
    from .udef_arp_qgis import UDef_ARP_QGIS
    return UDef_ARP_QGIS(iface)
